import { emptyProperty } from './constants';
import type { Agent, Client, Deal, Owner, Property, PropertyPhoto, Publication } from './types';

export const fallbackPhotos: PropertyPhoto[] = [
  {
    id: 'url-vake-living',
    name: 'Living room',
    src: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    type: 'url',
  },
  {
    id: 'url-vake-bedroom',
    name: 'Bedroom',
    src: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
    type: 'url',
  },
  {
    id: 'url-vake-kitchen',
    name: 'Kitchen',
    src: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80',
    type: 'url',
  },
];

const starterProperties: Property[] = [
  {
    ...emptyProperty,
    id: 'RIT-1001',
    dealType: 'Rent',
    category: 'Apartment',
    city: 'Tbilisi',
    district: 'Vake',
    metro: 'Rustaveli',
    address: 'Ilia Chavchavadze Ave 37',
    mapLink: 'https://maps.google.com/',
    cadastralCode: '',
    building: 'Axis Towers area',
    source: 'Owner',
    titleRu: 'Светлая квартира в Vake',
    titleEn: 'Beautiful apartment for rent in Vake',
    descriptionRu: 'Светлая квартира рядом с парком, готова к показам.',
    descriptionEn: 'Bright apartment near Vake Park, ready for viewings.',
    price: '1200',
    currency: '$',
    area: '72',
    bedrooms: '2',
    rooms: '3',
    floor: '8',
    totalFloors: '12',
    tenantsCount: '1-4',
    buildingType: 'NewBuilding',
    renovation: 'White',
    heating: 'CentralHeating',
    balcony: true,
    elevator: true,
    dishwasher: true,
    oven: true,
    stove: true,
    tv: true,
    vacuumCleaner: true,
    shower: true,
    fridge: true,
    washingMachine: true,
    internet: true,
    deposit: '1200',
    taxIncluded: false,
    owner: 'Giorgi Maisuradze',
    ownerPhone: '+995 599 10 20 30',
    ownerTelegram: '@giorgi_owner',
    publicationContact: '@David_Tibelashvili',
    status: 'On Advertising',
    exclusive: true,
    internalNotes: 'Показы после 18:00. Ключи у консьержа.',
    photos: fallbackPhotos,
    mainPhotoId: fallbackPhotos[0].id,
    videoUrl: '',
    videoMeta: null,
    createdAt: '2026-07-01T10:00:00.000Z',
    updatedAt: '2026-07-01T10:00:00.000Z',
  },
  {
    ...emptyProperty,
    id: 'RIT-1002',
    dealType: 'Sale',
    category: 'Apartment',
    city: 'Tbilisi',
    district: 'Sololaki',
    metro: 'LibertySquare',
    address: 'Atoneli St 12',
    mapLink: 'https://maps.google.com/',
    cadastralCode: '',
    building: 'Old Tbilisi residence',
    source: 'Owner',
    titleRu: 'Квартира в историческом доме',
    titleEn: 'Apartment for sale in historic Sololaki',
    descriptionRu: 'Исторический дом, высокий потолок, чистые документы.',
    descriptionEn: 'Historic building, high ceiling, clear ownership documents.',
    price: '185000',
    currency: '$',
    area: '96',
    bedrooms: '3',
    rooms: '4',
    floor: '3',
    totalFloors: '5',
    tenantsCount: '',
    buildingType: 'HistoricalBuilding',
    renovation: 'Mixed',
    heating: 'CentralHeating',
    balcony: true,
    oven: true,
    stove: true,
    tv: true,
    vacuumCleaner: true,
    shower: true,
    fridge: true,
    internet: true,
    taxIncluded: true,
    owner: 'Mariam Janelidze',
    ownerPhone: '+995 577 44 55 66',
    ownerTelegram: '@mariam_owner',
    publicationContact: '@David_Tibelashvili',
    status: 'Sold',
    exclusive: false,
    internalNotes: 'Сделка закрыта, документы в архиве.',
    photos: [
      {
        id: 'url-sololaki-main',
        name: 'Sololaki apartment',
        src: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
        type: 'url',
      },
    ],
    mainPhotoId: 'url-sololaki-main',
    videoUrl: '',
    videoMeta: null,
    createdAt: '2026-06-28T12:20:00.000Z',
    updatedAt: '2026-06-28T12:20:00.000Z',
  },
  {
    ...emptyProperty,
    id: 'RIT-1003',
    dealType: 'Rent',
    category: 'Apartment',
    city: 'Tbilisi',
    district: 'Saburtalo',
    metro: 'MCUniversity',
    address: 'Bakhtrioni St 22',
    mapLink: 'https://maps.google.com/',
    cadastralCode: '',
    source: 'Owner',
    titleRu: 'Уютная квартира у метро',
    titleEn: 'Cozy apartment near metro',
    descriptionRu: 'Подходит для пары или одного человека, можно с маленьким питомцем.',
    descriptionEn: 'Good fit for one person or a couple, small pets negotiable.',
    price: '850',
    currency: '$',
    area: '61',
    bedrooms: '1',
    rooms: '2',
    floor: '6',
    totalFloors: '10',
    tenantsCount: '1-2',
    buildingType: 'NewBuilding',
    renovation: 'Grey',
    heating: 'CentralHeating',
    balcony: true,
    elevator: true,
    oven: true,
    stove: true,
    tv: true,
    vacuumCleaner: true,
    shower: true,
    fridge: true,
    washingMachine: true,
    internet: true,
    petPolicy: 'ByAgreement',
    deposit: '850',
    taxIncluded: false,
    owner: 'Irakli Nadiradze',
    ownerPhone: '+995 555 77 88 90',
    ownerTelegram: '@irakli_owner',
    publicationContact: '@David_Tibelashvili',
    status: 'In Progress',
    exclusive: true,
    internalNotes: 'Нужен новый фотоотчет перед публикацией.',
    photos: [
      {
        id: 'url-saburtalo-main',
        name: 'Saburtalo apartment',
        src: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80',
        type: 'url',
      },
    ],
    mainPhotoId: 'url-saburtalo-main',
    videoUrl: '',
    videoMeta: null,
    createdAt: '2026-06-20T09:10:00.000Z',
    updatedAt: '2026-06-20T09:10:00.000Z',
  },
];

const extraSeedProperties: Property[] = [
  ['RIT-1004', 'Rent', 'Vera', 'Rustaveli', '25 Barnovi Street', '980', '58', '1', '4', '9', 'Rented', 'Nino Beridze'],
  ['RIT-1005', 'Rent', 'Saburtalo', 'MCUniversity', '14b Shalva Nutsubidze Street', '1000', '105', '2', '5', '12', 'On Advertising', 'David Tibelashvili'],
  ['RIT-1006', 'Sale', 'Vake', 'Delisi', 'Mtskheta Street 18', '245000', '118', '3', '6', '14', 'On Advertising', 'Ana Lomidze'],
  ['RIT-1007', 'Rent', 'DidiDigomi', 'Didube', 'Mirian Mepe Avenue 41', '650', '72', '2', '3', '8', 'In Progress', 'Nino Beridze'],
  ['RIT-1008', 'Sale', 'Krtsanisi', '300Aragveli', 'Krtsanisi Residence', '320000', '140', '3', '9', '12', 'Sold', 'David Tibelashvili'],
  ['RIT-1009', 'Rent', 'Varketili', 'Varketili', 'Javakheti Street 7', '480', '46', '1', '2', '9', 'Archived', 'Mari Operator'],
  ['RIT-1010', 'Daily Rent', 'Avlabari', 'AvlabariMetro', 'Metekhi Rise 4', '95', '38', '1', '2', '4', 'New', 'Ana Lomidze'],
].map(([id, dealType, district, metro, address, price, area, bedrooms, floor, totalFloors, status, agent], index) => {
  const photo = {
    id: `${id}-photo`,
    name: `${district} apartment`,
    src: fallbackPhotos[index % fallbackPhotos.length].src,
    type: 'url' as const,
  };
  return {
    ...emptyProperty,
    id,
    dealType: dealType as Property['dealType'],
    category: 'Apartment',
    city: 'Tbilisi',
    district,
    metro,
    address,
    mapLink: 'https://maps.google.com/',
    source: 'Owner',
    building: 'Residential building',
    titleRu: `${district} ${dealType === 'Rent' ? 'аренда' : 'продажа'}`,
    titleEn: `${bedrooms} bedroom apartment in ${district}`,
    descriptionRu: 'Seed объект для аналитики и проверки CRM.',
    descriptionEn: 'Seed listing for CRM analytics and QA.',
    price,
    area,
    bedrooms,
    rooms: String(Number(bedrooms) + 1),
    floor,
    totalFloors,
    tenantsCount: dealType === 'Sale' ? '' : '1-4',
    buildingType: index % 3 === 0 ? 'OldBuilding' : 'NewBuilding',
    renovation: index % 2 === 0 ? 'White' : 'Grey',
    heating: 'CentralHeating',
    balcony: true,
    elevator: true,
    oven: true,
    stove: true,
    tv: true,
    vacuumCleaner: true,
    shower: true,
    internet: true,
    parking: index % 2 === 0,
    airConditioner: true,
    petPolicy: 'ByAgreement',
    deposit: dealType === 'Sale' ? '' : price,
    owner: `Owner ${index + 4}`,
    ownerPhone: '+995 599 20 67 16',
    ownerTelegram: '@owner_seed',
    status: status as Property['status'],
    exclusive: index % 2 === 0,
    agent,
    operator: 'Mari',
    publicationContact: '@David_Tibelashvili',
    photos: [photo],
    mainPhotoId: photo.id,
    videoUrl: '',
    videoMeta: null,
    createdAt: `2026-07-0${Math.min(index + 1, 8)}T10:00:00.000Z`,
    updatedAt: `2026-07-0${Math.min(index + 1, 8)}T12:00:00.000Z`,
  };
});

export const seedProperties = [...starterProperties, ...extraSeedProperties];

export const starterAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'David Tibelashvili',
    telegram: '@David_Tibelashvili',
    phone: '+995 599 20 67 16',
    role: 'Администратор',
    dealsCount: 42,
    exclusiveCount: 22,
    commissionPercent: 0,
    isActive: true,
  },
  {
    id: 'agent-2',
    name: 'Mari Operator',
    telegram: '@mari_molecula',
    phone: '+995 577 44 55 66',
    role: 'Оператор',
    dealsCount: 15,
    exclusiveCount: 8,
    commissionPercent: 0,
    isActive: true,
  },
  {
    id: 'agent-3',
    name: 'Nino Beridze',
    telegram: '@nino_molecula',
    phone: '+995 599 10 20 30',
    role: 'Агент 70%',
    dealsCount: 18,
    exclusiveCount: 9,
    commissionPercent: 70,
    isActive: true,
  },
  {
    id: 'agent-4',
    name: 'Ana Lomidze',
    telegram: '@ana_molecula',
    phone: '+995 555 77 88 90',
    role: 'Агент 50%',
    dealsCount: 11,
    exclusiveCount: 5,
    commissionPercent: 50,
    isActive: true,
  },
  {
    id: 'agent-5',
    name: 'Sergi Matchavariani',
    telegram: '@sergi_molecula',
    phone: '+995 599 88 77 66',
    role: 'Агент 90%',
    dealsCount: 27,
    exclusiveCount: 16,
    commissionPercent: 90,
    isActive: true,
  },
];

export const starterOwners: Owner[] = [
  {
    id: 'owner-1',
    name: 'Giorgi Maisuradze',
    phone: '+995 599 10 20 30',
    telegram: '@giorgi_owner',
    objects: ['RIT-1001'],
    language: 'RU/EN',
    notes: 'Предпочитает сообщения в Telegram.',
    trustManagement: true,
  },
  {
    id: 'owner-2',
    name: 'Mariam Janelidze',
    phone: '+995 577 44 55 66',
    telegram: '@mariam_owner',
    objects: ['RIT-1002'],
    language: 'RU',
    notes: 'Документы проверены.',
    trustManagement: false,
  },
  {
    id: 'owner-3',
    name: 'Irakli Nadiradze',
    phone: '+995 555 77 88 90',
    telegram: '@irakli_owner',
    objects: ['RIT-1003'],
    language: 'EN',
    notes: 'Готов к эксклюзиву после первой сдачи.',
    trustManagement: true,
  },
  {
    id: 'owner-4',
    name: 'Natia Dolidze',
    phone: '+995 598 44 33 22',
    telegram: '@natia_owner',
    objects: ['RIT-1006'],
    language: 'GE/RU',
    notes: 'Просит отчеты по показам каждую неделю.',
    trustManagement: false,
  },
  {
    id: 'owner-5',
    name: 'Saba Kordzaia',
    phone: '+995 557 22 11 00',
    telegram: '@saba_owner',
    objects: ['RIT-1008'],
    language: 'EN',
    notes: 'Инвестор, несколько объектов в работе.',
    trustManagement: true,
  },
];

export const starterClients: Client[] = [
  {
    id: 'client-1',
    name: 'Elena Petrova',
    phone: '+995 551 00 11 22',
    telegram: '@elena_tb',
    budget: '900-1300$',
    request: '2 bedroom in Vake or Vera',
    district: 'Vake',
    status: 'Активный поиск',
    agent: 'Nino Beridze',
    notes: 'Нужен лифт и pet friendly.',
  },
  {
    id: 'client-2',
    name: 'Mark Wilson',
    phone: '+995 555 10 20 30',
    telegram: '@mark_tbilisi',
    budget: '200000-280000$',
    request: 'Sale apartment in Vake',
    district: 'Vake',
    status: 'Viewing',
    agent: 'Ana Lomidze',
    notes: 'Interested in new buildings.',
  },
  {
    id: 'client-3',
    name: 'Anna Schmidt',
    phone: '+995 577 12 12 12',
    telegram: '@anna_schmidt',
    budget: '700-1000$',
    request: '1Bed near metro',
    district: 'Saburtalo',
    status: 'Active',
    agent: 'Nino Beridze',
    notes: 'Needs contract for 12 months.',
  },
  {
    id: 'client-4',
    name: 'Giorgi Investor',
    phone: '+995 599 55 44 33',
    telegram: '@giorgi_invest',
    budget: '300000$',
    request: 'Commercial or hotel opportunity',
    district: 'Old Tbilisi',
    status: 'Warm',
    agent: 'David Tibelashvili',
    notes: 'Asks for cap rate.',
  },
  {
    id: 'client-5',
    name: 'Kate Novak',
    phone: '+995 551 91 91 91',
    telegram: '@kate_novak',
    budget: 'Daily 80-120$',
    request: 'Daily rent in old city',
    district: 'Avlabari',
    status: 'New',
    agent: 'Sergi Matchavariani',
    notes: 'Arrives next week.',
  },
];

export const starterDeals: Deal[] = [
  {
    id: 'deal-1',
    propertyId: 'RIT-1002',
    client: 'Private buyer',
    owner: 'Mariam Janelidze',
    agent: 'David Tibelashvili',
    dealType: 'Sale',
    amount: '185000$',
    commission: '3%',
    date: '2026-06-28',
    status: 'Закрыта',
    notes: 'Успешная продажа.',
  },
  {
    id: 'deal-2',
    propertyId: 'RIT-1004',
    client: 'Anna Schmidt',
    owner: 'Owner 4',
    agent: 'Nino Beridze',
    dealType: 'Rent',
    amount: '980$',
    commission: '490$',
    date: '2026-07-07',
    status: 'Closed',
    notes: 'Rented this week.',
  },
  {
    id: 'deal-3',
    propertyId: 'RIT-1008',
    client: 'Private buyer',
    owner: 'Saba Kordzaia',
    agent: 'David Tibelashvili',
    dealType: 'Sale',
    amount: '320000$',
    commission: '9600$',
    date: '2026-07-03',
    status: 'Closed',
    notes: 'Premium sale.',
  },
  {
    id: 'deal-4',
    propertyId: 'RIT-1001',
    client: 'Elena Petrova',
    owner: 'Giorgi Maisuradze',
    agent: 'David Tibelashvili',
    dealType: 'Rent',
    amount: '1200$',
    commission: '600$',
    date: '2026-07-02',
    status: 'Signed',
    notes: 'Waiting for payment.',
  },
  {
    id: 'deal-5',
    propertyId: 'RIT-1006',
    client: 'Mark Wilson',
    owner: 'Natia Dolidze',
    agent: 'Ana Lomidze',
    dealType: 'Sale',
    amount: '245000$',
    commission: '7350$',
    date: '2026-07-05',
    status: 'New',
    notes: 'Negotiation stage.',
  },
];

export const starterPublications: Publication[] = [
  {
    id: 'pub-1',
    propertyId: 'RIT-1001',
    propertyTitle: 'Beautiful apartment for rent in Vake',
    date: '2026-07-08T09:30:00.000Z',
    author: 'David Tibelashvili',
    channel: 'Demo',
    status: 'Copied',
    text: 'Seed Telegram post',
    photosCount: 3,
  },
  {
    id: 'pub-2',
    propertyId: 'RIT-1005',
    propertyTitle: '2 bedroom apartment in Saburtalo',
    date: '2026-07-07T11:00:00.000Z',
    author: 'Sergi Matchavariani',
    channel: 'Test',
    status: 'Test Published',
    text: 'Seed test channel post',
    photosCount: 1,
    messageLink: 'https://t.me/rentintbilisi_test/1',
  },
  {
    id: 'pub-3',
    propertyId: 'RIT-1006',
    propertyTitle: '3 bedroom apartment in Vake',
    date: '2026-07-03T14:30:00.000Z',
    author: 'Ana Lomidze',
    channel: 'Demo',
    status: 'Draft',
    text: 'Seed draft post',
    photosCount: 1,
  },
  {
    id: 'pub-4',
    propertyId: 'RIT-1008',
    propertyTitle: 'Premium sale in Krtsanisi',
    date: '2026-07-02T17:15:00.000Z',
    author: 'David Tibelashvili',
    channel: 'Production',
    status: 'Production Published',
    text: 'Seed production post',
    photosCount: 1,
    messageLink: 'https://t.me/rentintbilisi/1',
  },
  {
    id: 'pub-5',
    propertyId: 'RIT-1003',
    propertyTitle: 'Cozy apartment near metro',
    date: '2026-06-29T10:45:00.000Z',
    author: 'Nino Beridze',
    channel: 'Demo',
    status: 'Error',
    text: 'Seed failed post',
    photosCount: 1,
    error: 'Backend not connected',
  },
];
