export const PROPERTY_STATUSES = ['Новый','Проверка','Закреплён','Нужна фотосъёмка','Фото готовы','Готов к публикации','Опубликован','Обновление','Показ','Переговоры','Договор','Сдан','Продан','Архив','Отклонён'] as const;
export const PROPERTY_SOURCES = ['Сайт','Рекомендация','Звонок','Социальные сети','Другое'] as const;
export const PROPERTY_TYPES = ['Квартира','Дом','Земля','Коммерция','Ритейл','Бизнес','Кафе','Ресторан','Салон красоты','Склад','Производство','Дуплекс','Таунхаус'] as const;
export const BEDROOMS = ['Студия','1','2','3','4','5','6+'] as const;
export const BUILDING_TYPES = ['Новостройка','Старый фонд','Историческое здание','Реконструкция'] as const;
export const PROPERTY_CONDITIONS = ['Чёрный каркас','Белый каркас','Зелёный каркас','Полностью отремонтирован'] as const;
export const DESIGNS = ['Новый','Белый','Серый','Жёлтый','Смешанный','Старый','Ретро','Требует ремонта'] as const;
export const PET_POLICIES = ['Разрешены','Запрещены','По договорённости'] as const;
export const CURRENCIES = ['USD','GEL','EUR'] as const;
export const DEAL_TYPES = ['Аренда','Продажа'] as const;
export type PropertyStatus=typeof PROPERTY_STATUSES[number]; export type PropertySource=typeof PROPERTY_SOURCES[number]; export type PropertyType=typeof PROPERTY_TYPES[number]; export type Currency=typeof CURRENCIES[number];
export type DealType=typeof DEAL_TYPES[number]; export type BedroomOption=typeof BEDROOMS[number]; export type BuildingType=typeof BUILDING_TYPES[number]; export type PropertyCondition=typeof PROPERTY_CONDITIONS[number]; export type Design=typeof DESIGNS[number]; export type PetPolicy=typeof PET_POLICIES[number];
export type HistoryField='Создание'|'Цена'|'Статус'|'Собственник'|'Агент';
export type PropertyHistoryEntry={id:string;field:HistoryField;previousValue:string;newValue:string;createdAt:string;action:string;author:'Пользователь'};
export type AmenityKey='elevator'|'oven'|'parking'|'airConditioner'|'balcony'|'terrace'|'yard'|'wifi'|'television'|'bathtub'|'shower'|'dishwasher'|'stove'|'microwave'|'vacuum'|'fireplace';
export type Amenities=Record<AmenityKey,boolean>;
export type MediaItem={id:string;type:'photo'|'video';name:string;mimeType:string;size:number;order:number;isPrimary:boolean;isOriginal:boolean;previewDataUrl:string;watermark:{enabled:boolean;version:null}};
export type TelegramPublicationMetadata={publicationId:string;publishedAt:string;channel:string;messageId:string;draftVersion:number|null};
export type Property={
  id:string; dealType:DealType; exclusive:boolean; description:string; district:string; metro:string; address:string; googleMapsUrl:string;
  propertyType:PropertyType; bedrooms:BedroomOption; buildingType:BuildingType|''; area:number|null; floor:number|null; totalFloors:number|null; design:Design|''; maxTenants:number|null; condition:PropertyCondition|'';
  bathrooms:number|null; heatingType:string; amenities:Amenities; pets:PetPolicy;
  price:number; deposit:number|null; priceRange:string; rentalTerm:string; salePriceRange:string; currency:Currency;
  agent:string; recruit:string; agentTelegram:string; agentPhone:string;
  ownerName:string; ownerPhone:string; cadastralNumber:string; comment:string; exclusiveStatus:string;
  media:MediaItem[];
  internalId:string; source:PropertySource; sourceUrl:string; status:PropertyStatus;
  createdAt:string; updatedAt:string; history:PropertyHistoryEntry[]; telegramPublication:TelegramPublicationMetadata;
};
export type PropertyInput=Omit<Property,'id'|'createdAt'|'updatedAt'|'history'>;
export const EMPTY_AMENITIES:Amenities={elevator:false,oven:false,parking:false,airConditioner:false,balcony:false,terrace:false,yard:false,wifi:false,television:false,bathtub:false,shower:false,dishwasher:false,stove:false,microwave:false,vacuum:false,fireplace:false};
export const EMPTY_TELEGRAM_METADATA:TelegramPublicationMetadata={publicationId:'',publishedAt:'',channel:'',messageId:'',draftVersion:null};
export const EMPTY_PROPERTY_INPUT:PropertyInput={dealType:'Аренда',exclusive:false,description:'',district:'',metro:'',address:'',googleMapsUrl:'',propertyType:'Квартира',bedrooms:'1',buildingType:'',area:null,floor:null,totalFloors:null,design:'',maxTenants:null,condition:'',bathrooms:null,heatingType:'',amenities:{...EMPTY_AMENITIES},pets:'По договорённости',price:0,deposit:null,priceRange:'',rentalTerm:'',salePriceRange:'',currency:'USD',agent:'',recruit:'',agentTelegram:'',agentPhone:'',ownerName:'',ownerPhone:'',cadastralNumber:'',comment:'',exclusiveStatus:'',media:[],internalId:'',source:'Сайт',sourceUrl:'',status:'Новый',telegramPublication:{...EMPTY_TELEGRAM_METADATA}};
