export type DealTypeId='rent'|'sale';
export type TaxonomyCategory='dealType'|'metro'|'district'|'buildingType'|'amenity'|'bedrooms'|'propertyType'|'rentalPeriod'|'design'|'pets'|'condition'|'residentialSubtype'|'commercialType'|'priceRange';
export type TaxonomyItem={id:string;labelRu:string;labelEn:string;hashtag:string;category:TaxonomyCategory;dealTypes:DealTypeId[];active:boolean;sortOrder:number};
const labels:Record<string,string>={LibertySquare:'Площадь Свободы',StationSquare:'Вокзальная площадь',TCUniversity:'Технический университет',STUniversity:'Государственный университет',MCUniversity:'Медицинский университет',NewBuilding:'Новостройка',OldBuilding:'Старый фонд',HistoricalBuilding:'Историческое здание',Reconstruction:'Реконструкция',Apartment:'Квартира',House:'Дом',Commercial:'Коммерция',Land:'Земля',Duplex:'Дуплекс',Townhouse:'Таунхаус',Retail:'Ритейл',Business:'Бизнес',Cafe:'Кафе',Restaurant:'Ресторан',BeautySalon:'Салон красоты',Warehouses:'Склад',Manufacture:'Производство',Studio:'Студия',New:'Новый',White:'Белый',Grey:'Серый',Yellow:'Жёлтый',Mixed:'Смешанный',Old:'Старый',Retro:'Ретро',UnderRepair:'Требует ремонта',NewApartment:'Новая квартира',BlackFrame:'Чёрный каркас',WhiteFrame:'Белый каркас',GreenFrame:'Зелёный каркас',FullyRenovated:'Полностью отремонтирован',Allowed:'Разрешены',NotAllowed:'Запрещены',ByAgreement:'По договорённости',Bath:'Ванна',Shower:'Душ',Balcony:'Балкон',Terrace:'Терраса',Courtyard:'Двор',ParkingPlace:'Парковочное место',Conditioner:'Кондиционер',Dishwasher:'Посудомоечная машина',Oven:'Духовка',Stove:'Плита',CentralHeating:'Центральное отопление',Fireplace:'Камин',GasHeating:'Газовое отопление',ElectricalHeating:'Электрическое отопление',ACHeating:'Отопление кондиционером',VacuumCleaner:'Пылесос',WiFi:'Wi-Fi',TV:'Телевизор',Microwave:'Микроволновка',Elevator:'Лифт'};
const ruAliases:Record<string,string>={Rustaveli:'Руставели',Marjanishvili:'Марджанишвили',Tsereteli:'Церетели',Gotsiridze:'Гоциридзе',Nadzaladevi:'Надзаладеви',Didube:'Дидубе',Grmagele:'Грмагеле',Guramishvili:'Гурамишвили',Sarajishvili:'Сараджишвили',AhmeteliTheatre:'Театр Ахметели',VazhaPshavela:'Важа-Пшавела',Delisi:'Делиси',AvlabariMetro:'Метро Авлабари',IsaniMetro:'Метро Исани','300Aragveli':'300 Арагвели',SamgoriMetro:'Метро Самгори',Varketili:'Варкетили',Vera:'Вера',Mtatsminda:'Мтацминда',Vake:'Ваке',Sololaki:'Сололаки',Kukia:'Кукиа',Naxalovka:'Нахаловка',SavnetisUbani:'Савнетис Убани',Tskneti:'Цхнети',Chugureti:'Чугурети',Nutsubidze:'Нуцубидзе',Saburtalo:'Сабуртало',Gldani:'Глдани',Avlabari:'Авлабари',Isani:'Исани',Samgori:'Самгори',Digomi:'Дигоми',DidiDigomi:'Диди Дигоми',DigomiMassive:'Массив Дигоми',Digomi1to9:'Дигоми 1–9',Ortachala:'Ортачала',Abanotubani:'Абанотубани',Saguramo:'Сагурамо',Krtsanisi:'Крцаниси',Vashlijvari:'Вашлиджвари',Temqa:'Темка',Iverubani:'Иверубани',Vazisubani:'Вазисубани',Afrika:'Африка',QvemoPonichala:'Квемо Поничала',Ponichala:'Поничала',Avchala:'Авчала',Bagebi:'Багеби',Lisi:'Лиси',Tskhneti:'Цхнети',OutOfTown:'За городом',Yard:'Участок'};
const human=(tag:string)=>labels[tag]??ruAliases[tag]??tag.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^Price/,'Цена ');
const make=(category:TaxonomyCategory,dealTypes:DealTypeId[],tags:string[]):TaxonomyItem[]=>[...new Set(tags)].map((tag,index)=>({id:`${category}.${tag}`,labelRu:human(tag),labelEn:tag.replace(/([a-z])([A-Z])/g,'$1 $2'),hashtag:`#${tag}`,category,dealTypes,active:true,sortOrder:index+1}));
const both:DealTypeId[]=['rent','sale'];
const RAW_TAXONOMY:TaxonomyItem[]=[
 ...make('dealType',['rent'],['Rent']),...make('dealType',['sale'],['Sale']),
 ...make('metro',both,['LibertySquare','Rustaveli','Marjanishvili','StationSquare','Tsereteli','Gotsiridze','Nadzaladevi','Didube','Grmagele','Guramishvili','Sarajishvili','AhmeteliTheatre','STUniversity','VazhaPshavela','Delisi','TCUniversity','MCUniversity','AvlabariMetro','IsaniMetro','300Aragveli','SamgoriMetro','Varketili']),
 ...make('district',both,['Vera','Mtatsminda','Vake','Sololaki','Kukia','Nadzaladevi','Naxalovka','SavnetisUbani','Tskneti','Chugureti','VazhaPshavela','Nutsubidze','Saburtalo','Didube','Gldani','Avlabari','Isani','Samgori','Digomi','DidiDigomi','DigomiMassive','Digomi1to9','Varketili','Ortachala','Abanotubani','Saguramo','Krtsanisi','Vashlijvari','Temqa','Iverubani','Vazisubani','Afrika','QvemoPonichala','Ponichala','Avchala','Bagebi','Lisi','Tskhneti','OutOfTown']),
 ...make('buildingType',both,['NewBuilding','OldBuilding','HistoricalBuilding','Reconstruction']),
 ...make('amenity',both,['Bath','Shower','Balcony','2Bathroom','3Bathroom','4Bathroom','Terrace','Courtyard','ParkingPlace','Conditioner','Dishwasher','Oven','Stove','CentralHeating','Fireplace']),
 ...make('bedrooms',['rent'],['1Bed','2Bed','3Bed','4Bed']),...make('propertyType',['rent'],['Apartment','House','Commercial']),
 ...make('rentalPeriod',['rent'],['1Day','1Month','2Month','3Month','4Month','5Month','6Month','12Month']),
 ...make('design',['rent'],['New','White','Grey','Yellow','Mixed','Old','Retro','UnderRepair']),
 ...make('amenity',['rent'],['GasHeating','ElectricalHeating','ACHeating','VacuumCleaner','WiFi','TV','Microwave','Elevator']),...make('pets',['rent'],['Allowed','NotAllowed','ByAgreement']),
 ...make('priceRange',['rent'],['Price0to300','Price300to500','Price500to700','Price700to900','Price900to1200','Price1200plus']),
 ...make('condition',['sale'],['BlackFrame','WhiteFrame','GreenFrame','FullyRenovated']),...make('amenity',['sale'],['Elevator']),
 ...make('priceRange',['sale'],['Price0to30000','Price30000to50000','Price50000to70000','Price70000to90000','Price90000to120000','Price120000to150000','Price150000to180000','Price180000to210000','Price210000to240000','Price240000to270000','Price270000to300000','Price300000to330000','Price330000to360000','Price360000to390000','Price390000to420000','Price420000to450000','Price450000to480000','Price480000to510000','Price510000to600000','Price600000to700000','Price700000to800000','Price800000to900000','Price900000to1000000','Price1000000plus']),
 ...make('bedrooms',['sale'],['Studio','1Bed','2Bed','3Bed','4Bed','5Bed','6Bedplus']),...make('propertyType',['sale'],['Apartment']),...make('residentialSubtype',['sale'],['Duplex','Townhouse','House','Land']),...make('commercialType',['sale'],['Yard','Courtyard','Commercial','Retail','Business','Cafe','Restaurant','BeautySalon','Warehouses','Manufacture']),
 ...make('design',['sale'],['White','Grey','Yellow','NewApartment','Mixed','Old','Retro','UnderRepair'])
];
export const TAXONOMY:TaxonomyItem[]=Array.from(RAW_TAXONOMY.reduce((map,item)=>{const key=`${item.category}:${item.hashtag}`;const existing=map.get(key);if(existing)existing.dealTypes=[...new Set([...existing.dealTypes,...item.dealTypes])];else map.set(key,{...item,dealTypes:[...item.dealTypes]});return map},new Map<string,TaxonomyItem>()).values()).map(item=>item.id==='bedrooms.Studio'?{...item,sortOrder:0}:item);
export const taxonomyById=(id:string)=>TAXONOMY.find(item=>item.id===id);
export const taxonomyIdFromValue=(category:TaxonomyCategory,value:unknown,dealType:DealTypeId)=>{const text=String(value??'').replace(/^#/,'').replace(/\s/g,'').toLowerCase();return TAXONOMY.find(item=>item.category===category&&item.dealTypes.includes(dealType)&&(item.id.toLowerCase()===String(value).toLowerCase()||item.hashtag.slice(1).toLowerCase()===text||item.labelRu.replace(/\s/g,'').toLowerCase()===text))?.id??''};
