import type { HistoryField, Property, PropertyHistoryEntry, PropertyInput } from '../domain/property';
import type { PropertyRepository } from '../repositories/propertyRepository';
const uid=()=>crypto.randomUUID();
const trim=(input:PropertyInput):PropertyInput=>({...input,description:input.description.trim(),address:input.address.trim(),googleMapsUrl:input.googleMapsUrl.trim(),agentId:input.agentId.trim(),agentHashtag:input.agentHashtag.trim().replace(/^#/,''),ownerName:input.ownerName.trim(),ownerPhone:input.ownerPhone.trim(),cadastralNumber:input.cadastralNumber.trim(),comment:input.comment.trim(),exclusiveStatus:input.exclusiveStatus.trim(),internalId:input.internalId.trim(),sourceUrl:input.sourceUrl.trim()});
const event=(field:HistoryField,previousValue:string,newValue:string,action:string):PropertyHistoryEntry=>({id:uid(),field,previousValue,newValue,createdAt:new Date().toISOString(),action,author:'Пользователь'});
export const validateProperty=(input:PropertyInput)=>{const e:Partial<Record<keyof PropertyInput,string>>={};if(!input.internalId.trim())e.internalId='Укажите внутренний ID.';if(!input.address.trim())e.address='Укажите адрес.';if(!input.districtId)e.districtId='Укажите район.';if(!input.bedroomsId)e.bedroomsId='Укажите спальни.';if(input.dealType==='rent'&&!input.propertyTypeId)e.propertyTypeId='Укажите тип объекта.';if(input.dealType==='sale'&&!input.propertyTypeId&&!input.residentialSubtypeId&&!input.commercialTypeId)e.propertyTypeId='Укажите тип объекта.';if(input.price<=0)e.price='Цена должна быть больше нуля.';if(input.area!==null&&input.area<=0)e.area='Площадь должна быть больше нуля.';if(input.floor!==null&&input.floor<0)e.floor='Этаж не может быть отрицательным.';if(input.totalFloors!==null&&input.totalFloors<=0)e.totalFloors='Этажность должна быть больше нуля.';if(input.floor!==null&&input.totalFloors!==null&&input.floor>input.totalFloors)e.floor='Этаж не может быть выше этажности.';if(input.dealType==='rent'&&input.maxTenants!==null&&input.maxTenants<=0)e.maxTenants='Количество жильцов должно быть больше нуля.';if(input.dealType==='sale'&&!input.conditionId)e.conditionId='Укажите состояние объекта.';if(input.sourceUrl.trim())try{new URL(input.sourceUrl)}catch{e.sourceUrl='Введите корректную ссылку.'}if(input.googleMapsUrl.trim())try{new URL(input.googleMapsUrl)}catch{e.googleMapsUrl='Введите корректную ссылку Google Maps.'}return e};
export class PropertyService{constructor(private repository:PropertyRepository){}create(raw:PropertyInput){const input=trim(raw);if(this.repository.findDuplicates(input.internalId,'').length)throw new Error('Объект с таким внутренним ID уже существует.');const now=new Date().toISOString();const property:Property={...input,id:uid(),createdAt:now,updatedAt:now,history:[event('Создание','',input.internalId,'Создание объекта')]};this.repository.save(property);return property}update(current:Property,raw:PropertyInput,action='Редактирование объекта'){const input=trim(raw);if(this.repository.findDuplicates(input.internalId,'',current.id).length)throw new Error('Объект с таким внутренним ID уже существует.');const entries:PropertyHistoryEntry[]=[];const add=(field:HistoryField,a:string,b:string)=>{if(a!==b)entries.push(event(field,a,b,action))};add('Цена',`${current.price} ${current.currency}`,`${input.price} ${input.currency}`);add('Статус',current.status,input.status);add('Собственник',`${current.ownerName} · ${current.ownerPhone}`,`${input.ownerName} · ${input.ownerPhone}`);add('Агент',current.agentHashtag||'Не назначен',input.agentHashtag||'Не назначен');const saved:Property={...current,...input,updatedAt:new Date().toISOString(),history:[...entries,...current.history]};this.repository.save(saved);return saved}}
export const propertyService=(repository:PropertyRepository)=>new PropertyService(repository);

export const buildPublicationDraft=(property:Property)=>({dealType:property.dealType,districtId:property.districtId,metroId:property.metroId,bedroomsId:property.bedroomsId,propertyTypeId:property.propertyTypeId,residentialSubtypeId:property.residentialSubtypeId,commercialTypeId:property.commercialTypeId,buildingTypeId:property.buildingTypeId,designId:property.designId,conditionId:property.conditionId,amenityIds:property.amenityIds,petId:property.petId,rentalPeriodIds:property.rentalPeriodIds,price:property.price,deposit:property.deposit,agentId:property.agentId,agentHashtag:property.agentHashtag,media:[...property.media].sort((a,b)=>a.order-b.order)});
