import { Archive, ArrowLeft, Camera, CheckCircle2, ClipboardCheck, FilePlus2, Link2, Pencil, SearchCheck, UserRound } from 'lucide-react';
import { type ReactNode, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import type { Property, PropertyInput, PropertyStatus } from '../../domain/property';
import { propertyAccessService,AccessDeniedError } from '../../services/propertyAccessService';
import { currentUserService } from '../../services/currentUserService';
import { moderationService } from '../../services/moderationService';
import { canEditPropertyDirectly,canCreateChangeRequest } from '../../services/accessPolicy';
import { buildPublicationText } from '../../services/buildPublicationText';
import { getTaxonomyLabel } from '../../services/publicationTaxonomy';
import { formatDate, formatPrice, statusClass } from './property.formatters';
import './properties.css';

const tabs = ['Обзор','Собственник','Медиа','Публикации','Показы','Договоры','История'] as const;
type Tab = typeof tabs[number];
export default function PropertyDetailPage(){
  const {propertyId}=useParams(); const [params,setParams]=useSearchParams(); const [version,setVersion]=useState(0); const [message,setMessage]=useState('');
  const currentUser=currentUserService.getCurrentUser();let property:Property|null=null;let forbidden=params.get('forbidden')==='1';try{property=propertyId?propertyAccessService.getById(currentUser,propertyId):null}catch(error){if(error instanceof AccessDeniedError)forbidden=true;else throw error}const requested=params.get('tab'); const tab:Tab=tabs.includes(requested as Tab)?requested as Tab:'Обзор';
  if(forbidden)return <section className="page"><div className="compact-empty"><SearchCheck/><p className="eyebrow">Ошибка 403</p><h1>Доступ запрещён</h1><p>Этот объект закреплён за другим пользователем.</p><Link className="button" to="/properties">Вернуться в реестр</Link></div></section>;
  if(!property)return <section className="page"><div className="compact-empty"><SearchCheck/><h1>Объект не найден</h1><p>Возможно, он был удалён из локального хранилища.</p><Link className="button" to="/properties">Вернуться в реестр</Link></div></section>;
  const direct=canEditPropertyDirectly(currentUser,property);const ownRequests=moderationService.list(currentUser).filter(v=>v.propertyId===property.id);
  const update=(changes:Partial<PropertyInput>,action:string)=>{try{const reason=prompt(`Причина действия «${action}»:`,action);if(!reason)return;propertyAccessService.updateDirect(currentUser,property,{...toInput(property),...changes},reason);setVersion(v=>v+1);setMessage('Изменения сохранены.');}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось выполнить действие.');}};
  const request=(type:import('../../domain/access').ChangeRequestType,changes:Partial<Property>,reasonLabel:string,updateRequired=false)=>{const reason=prompt(reasonLabel);if(!reason)return;try{moderationService.create(currentUser,property.id,type,changes,reason,updateRequired);setVersion(v=>v+1);setMessage('Заявка отправлена на модерацию.')}catch(error){setMessage(error instanceof Error?error.message:'Не удалось создать заявку.')}};
  const priceRequest=()=>{const value=prompt(`Текущая цена: ${property.price}. Введите новую цену:`);if(!value)return;const price=Number(value);if(!Number.isFinite(price)||price<=0){setMessage('Введите корректную цену.');return}request('price_update',{price},'Причина изменения цены:',confirm('Отправить Update после одобрения?'))};
  const discountRequest=()=>{const value=prompt(`Текущая цена: ${property.price}. Предлагаемая цена:`);if(!value)return;const ownerComment=prompt('Комментарий собственника:')??'';const validUntil=prompt('Срок действия предложения:')??'';request('discount_request',{price:Number(value)},`Скидка: ${ownerComment}; действует до ${validUntil}`)};
  const assign=()=>{const agent=prompt('Введите хэштег ответственного агента:',property.agentHashtag);if(agent!==null&&agent.trim())update({agentHashtag:agent.replace(/^#/,''),status:property.status==='Новый'?'Закреплён':property.status},'Закрепление за агентом');};
  const duplicates=()=>alert('Проверка дублей доступна оператору через реестр перед сохранением.');
  const changeStatus=(status:PropertyStatus,action:string,question:string)=>{if(confirm(question))update({status},action);};
  void version;
  const typeId=property.propertyTypeId||property.residentialSubtypeId||property.commercialTypeId;
  return <section className="page property-detail"><Link className="back-link" to="/properties"><ArrowLeft size={17}/>К реестру</Link><header className="property-detail__header"><div><div className="property-detail__id"><span className={statusClass(property.status)}>{property.status}</span><span>{property.internalId}</span></div><h1>{property.address}</h1><p>{getTaxonomyLabel(property.districtId)} · {getTaxonomyLabel(typeId)} · обновлён {formatDate(property.updatedAt)}</p></div><div className="property-detail__price">{formatPrice(property.price,property.currency)}</div></header>
    {message&&<div className="action-message" role="status"><CheckCircle2 size={17}/>{message}<button onClick={()=>setMessage('')}>Закрыть</button></div>}
    <div className="property-actions">{direct?<><Link className="button" to={`/properties/${property.id}/edit`}><Pencil size={16}/>Редактировать</Link><button onClick={assign}><UserRound size={16}/>Закрепить</button><button onClick={duplicates}><SearchCheck size={16}/>Проверить дубли</button><button onClick={()=>changeStatus('Нужна фотосъёмка','Отправка на фотосъёмку','Изменить статус?')}><Camera size={16}/>На фотосъёмку</button><button onClick={()=>changeStatus('Готов к публикации','Создание публикации','Изменить статус?')}><Link2 size={16}/>Создать публикацию</button><button onClick={()=>changeStatus('Договор','Создание договора','Изменить статус?')}><FilePlus2 size={16}/>Создать договор</button><button className="danger-action" onClick={()=>changeStatus('Архив','Перенос в архив','Перенести объект в архив?')}><Archive size={16}/>В архив</button></>:canCreateChangeRequest(currentUser,property)&&<><Link className="button" to={`/properties/${property.id}/edit`}><Pencil size={16}/>Предложить изменение</Link><button onClick={priceRequest}>Изменить цену</button><button onClick={discountRequest}>Запросить скидку</button><button onClick={()=>request('media_update',{},'Опишите обновление медиа:')}>Обновить медиа</button><button onClick={()=>request('publication_request',{status:'Готов к публикации'},'Комментарий к публикации:')}>Отправить на публикацию</button><button onClick={()=>request('unpublish_request',{status:'Обновление'},'Причина снятия с публикации:')}>Снять с публикации</button></>}</div>
    {ownRequests.length>0&&<section className="request-summary"><h2>{direct?'Заявки по объекту':'Мои заявки'}</h2>{ownRequests.map(item=><div key={item.id}><strong>{item.type}</strong><span>{item.status}</span><small>{new Date(item.createdAt).toLocaleString('ru-RU')}</small></div>)}</section>}
    <nav className="property-tabs" aria-label="Разделы объекта">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setParams(item==='Обзор'?{}:{tab:item})}>{item}</button>)}</nav>
    <div className="property-tab-content">{tab==='Обзор'&&<Overview property={property}/>} {tab==='Собственник'&&<Owner property={property} onAssign={assign} direct={direct}/>} {tab==='История'&&<History property={property}/>} {tab==='Медиа'&&<Media property={property}/>} {tab==='Публикации'&&<PublicationPreview property={property}/>} {tab==='Показы'&&<TabEmpty icon={<ClipboardCheck/>} title="Показов пока нет" text="Зарегистрированные показы появятся здесь после реализации соответствующего сценария."/>} {tab==='Договоры'&&<TabEmpty icon={<FilePlus2/>} title="Договоров пока нет" text="Backend договоров не подключён. Действие выше изменяет рабочий статус объекта."/>}</div>
  </section>;
}
const toInput=({id,createdAt,updatedAt,history,...input}:Property):PropertyInput=>input;
function Overview({property}:{property:Property}){const type=property.propertyTypeId||property.residentialSubtypeId||property.commercialTypeId;return <div className="overview-sections"><Detail title="Сделка" items={[['Тип сделки',property.dealType==='rent'?'Аренда':'Продажа'],['Эксклюзив',property.exclusive?'Да':'Нет'],['Описание',property.description]]}/><Detail title="Локация" items={[['Район',getTaxonomyLabel(property.districtId)],['Метро',getTaxonomyLabel(property.metroId)],['Адрес',property.address],['Google Maps',property.googleMapsUrl]]}/><Detail title="Объект" items={[['Тип',getTaxonomyLabel(type)],['Спальни',getTaxonomyLabel(property.bedroomsId)],['Тип здания',getTaxonomyLabel(property.buildingTypeId)],['Площадь',property.area?`${property.area} м²`:null],['Этаж',property.floor],['Всего этажей',property.totalFloors],['Дизайн',getTaxonomyLabel(property.designId)],[property.dealType==='rent'?'Макс. жильцов':'Состояние',property.dealType==='rent'?property.maxTenants:getTaxonomyLabel(property.conditionId)]]}/><Detail title="Удобства" items={[['Количество ванных',property.bathrooms],['Оснащение',property.amenityIds.map(getTaxonomyLabel).join(', ')],['Питомцы',property.dealType==='rent'?getTaxonomyLabel(property.petId):null]]}/><Detail title="Цена" items={[['Цена',formatPrice(property.price,property.currency)],['Депозит',property.dealType==='rent'&&property.deposit?formatPrice(property.deposit,property.currency):null],['Срок',property.rentalPeriodIds.map(getTaxonomyLabel).join(', ')]]}/><Detail title="Агент" items={[['ID агента',property.agentId],['Хэштег',property.agentHashtag?`#${property.agentHashtag}`:'Не назначен'],['Контакт','@David_Tibelashvili · +995 599 20 67 16']]}/><Detail title="Собственник" items={[['Имя',property.ownerName],['Телефон',property.ownerPhone],['Кадастровый номер',property.cadastralNumber],['Статус эксклюзива',property.exclusiveStatus],['Комментарий',property.comment]]}/></div>}
function Detail({title,items}:{title:string;items:[string,string|number|null|false][]}){return <section className="detail-panel"><h2>{title}</h2><Definition items={items}/></section>}
function Media({property}:{property:Property}){return property.media.length?<div className="media-gallery">{[...property.media].sort((a,b)=>a.order-b.order).map(item=><article key={item.id}>{item.type==='photo'?<img src={item.previewDataUrl} alt={item.name}/>:<video src={item.previewDataUrl} controls/>}<strong>{item.name}</strong><small>{item.isPrimary?'Главное · ':''}Оригинал · watermark не применён</small></article>)}</div>:<TabEmpty icon={<Camera/>} title="Медиа пока нет" text="Добавьте локальные фото или видео в режиме редактирования объекта."/>}
function PublicationPreview({property}:{property:Property}){const text=buildPublicationText(property);const copy=async()=>{try{await navigator.clipboard.writeText(text);alert('Текст публикации скопирован.')}catch{alert('Не удалось скопировать текст. Выделите его вручную.')}};return <section className="publication-preview"><header><div><h2>Предпросмотр публикации</h2><p>Текст сформирован локально. Отправка в Telegram не выполняется.</p></div><button className="button" onClick={copy}>Копировать текст</button></header><pre>{text}</pre></section>}
function Owner({property,onAssign,direct}:{property:Property;onAssign:()=>void;direct:boolean}){return <div className="detail-panel owner-panel"><h2>Собственник</h2><Definition items={[['Имя',property.ownerName],['Телефон',property.ownerPhone]]}/><div className="inline-actions"><Link className="button button--secondary" to={`/properties/${property.id}/edit`}>{direct?'Редактировать данные':'Предложить изменение'}</Link>{direct&&<button className="button" onClick={onAssign}>Назначить агента</button>}</div></div>}
function History({property}:{property:Property}){return property.history.length?<div className="history-list">{property.history.map(item=><article key={item.id}><span className="history-dot"/><div><strong>{item.field}: {item.action}</strong><p>{item.previousValue&&<><s>{item.previousValue}</s> → </>}{item.newValue}</p><small>{formatDate(item.createdAt)} · {item.author}</small></div></article>)}</div>:<TabEmpty icon={<ClipboardCheck/>} title="История пуста" text="Изменения объекта будут записываться автоматически."/>}
function Definition({items}:{items:[string,string|number|boolean|null][]}){return <dl className="definition-list">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Не указано'}</dd></div>)}</dl>}
function TabEmpty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="tab-empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div>}
