import { Archive, ArrowLeft, Camera, CheckCircle2, ClipboardCheck, FilePlus2, Link2, Pencil, SearchCheck, UserRound } from 'lucide-react';
import { type ReactNode, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import type { Property, PropertyInput, PropertyStatus } from '../../domain/property';
import { propertyRepository } from '../../repositories/propertyRepository';
import { propertyService } from '../../services/propertyService';
import { formatDate, formatPrice, statusClass } from './property.formatters';
import './properties.css';

const tabs = ['Обзор','Собственник','Медиа','Публикации','Показы','Договоры','История'] as const;
type Tab = typeof tabs[number];
export default function PropertyDetailPage(){
  const {propertyId}=useParams(); const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const [version,setVersion]=useState(0); const [message,setMessage]=useState('');
  const property=propertyId?propertyRepository.getById(propertyId):null; const requested=params.get('tab'); const tab:Tab=tabs.includes(requested as Tab)?requested as Tab:'Обзор';
  if(!property)return <section className="page"><div className="compact-empty"><SearchCheck/><h1>Объект не найден</h1><p>Возможно, он был удалён из локального хранилища.</p><Link className="button" to="/properties">Вернуться в реестр</Link></div></section>;
  const update=(changes:Partial<PropertyInput>,action:string)=>{try{propertyService(propertyRepository).update(property,{...toInput(property),...changes},action);setVersion(v=>v+1);setMessage('Изменения сохранены.');}catch(reason){setMessage(reason instanceof Error?reason.message:'Не удалось выполнить действие.');}};
  const assign=()=>{const agent=prompt('Введите имя ответственного агента:',property.agent);if(agent!==null&&agent.trim())update({agent,status:property.status==='Новый'?'Закреплён':property.status},'Закрепление за агентом');};
  const duplicates=()=>{const matches=propertyRepository.findDuplicates(property.internalId,property.sourceUrl,property.id);alert(matches.length?`Найдено возможных дублей: ${matches.length}`:'Возможные дубли не найдены.');};
  const changeStatus=(status:PropertyStatus,action:string,question:string)=>{if(confirm(question))update({status},action);};
  void version;
  return <section className="page property-detail"><Link className="back-link" to="/properties"><ArrowLeft size={17}/>К реестру</Link><header className="property-detail__header"><div><div className="property-detail__id"><span className={statusClass(property.status)}>{property.status}</span><span>{property.internalId}</span></div><h1>{property.address}</h1><p>{property.district} · {property.propertyType} · обновлён {formatDate(property.updatedAt)}</p></div><div className="property-detail__price">{formatPrice(property.price,property.currency)}</div></header>
    {message&&<div className="action-message" role="status"><CheckCircle2 size={17}/>{message}<button onClick={()=>setMessage('')}>Закрыть</button></div>}
    <div className="property-actions"><Link className="button" to={`/properties/${property.id}/edit`}><Pencil size={16}/>Редактировать</Link><button onClick={assign}><UserRound size={16}/>Закрепить</button><button onClick={duplicates}><SearchCheck size={16}/>Проверить дубли</button><button onClick={()=>changeStatus('Нужна фотосъёмка','Отправка на фотосъёмку','Изменить статус на «Нужна фотосъёмка»?')}><Camera size={16}/>На фотосъёмку</button><button onClick={()=>changeStatus('Готов к публикации','Создание публикации','Создать локальный черновик публикации и изменить статус?')}><Link2 size={16}/>Создать публикацию</button><button onClick={()=>changeStatus('Договор','Создание договора','Начать локальный сценарий договора и изменить статус?')}><FilePlus2 size={16}/>Создать договор</button><button className="danger-action" onClick={()=>changeStatus('Архив','Перенос в архив','Перенести объект в архив?')}><Archive size={16}/>В архив</button></div>
    <nav className="property-tabs" aria-label="Разделы объекта">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setParams(item==='Обзор'?{}:{tab:item})}>{item}</button>)}</nav>
    <div className="property-tab-content">{tab==='Обзор'&&<Overview property={property}/>} {tab==='Собственник'&&<Owner property={property} onAssign={assign}/>} {tab==='История'&&<History property={property}/>} {tab==='Медиа'&&<Media property={property}/>} {tab==='Публикации'&&<TabEmpty icon={<Link2/>} title="Публикаций пока нет" text="Telegram не подключён. Данные объекта готовы для формирования черновика без повторного ввода."/>} {tab==='Показы'&&<TabEmpty icon={<ClipboardCheck/>} title="Показов пока нет" text="Зарегистрированные показы появятся здесь после реализации соответствующего сценария."/>} {tab==='Договоры'&&<TabEmpty icon={<FilePlus2/>} title="Договоров пока нет" text="Backend договоров не подключён. Действие выше изменяет рабочий статус объекта."/>}</div>
  </section>;
}
const toInput=({id,createdAt,updatedAt,history,...input}:Property):PropertyInput=>input;
function Overview({property}:{property:Property}){const amenities=Object.entries(property.amenities).filter(([,v])=>v).map(([k])=>({elevator:'Лифт',oven:'Духовка',parking:'Парковочное место',airConditioner:'Кондиционер',balcony:'Балкон',terrace:'Терраса',yard:'Двор',wifi:'Wi-Fi',television:'Телевизор',bathtub:'Ванна',shower:'Душ',dishwasher:'Посудомоечная машина',stove:'Плита',microwave:'Микроволновка',vacuum:'Пылесос',fireplace:'Камин'}[k]));return <div className="overview-sections"><Detail title="Сделка" items={[['Тип сделки',property.dealType],['Эксклюзив',property.exclusive?'Да':'Нет'],['Описание',property.description]]}/><Detail title="Локация" items={[['Район',property.district],['Метро',property.metro],['Адрес',property.address],['Google Maps',property.googleMapsUrl]]}/><Detail title="Объект" items={[['Тип',property.propertyType],['Спальни',property.bedrooms],['Тип здания',property.buildingType],['Площадь',property.area?`${property.area} м²`:null],['Этаж',property.floor],['Всего этажей',property.totalFloors],['Дизайн',property.design],[property.dealType==='Аренда'?'Макс. жильцов':'Состояние',property.dealType==='Аренда'?property.maxTenants:property.condition]]}/><Detail title="Удобства" items={[['Количество ванных',property.bathrooms],['Отопление',property.heatingType],['Питомцы',property.pets],['Оснащение',amenities.join(', ')]]}/><Detail title="Цена" items={[['Цена',formatPrice(property.price,property.currency)],['Депозит',property.dealType==='Аренда'&&property.deposit?formatPrice(property.deposit,property.currency):null],['Ценовой диапазон',property.dealType==='Аренда'?property.priceRange:property.salePriceRange],['Срок аренды',property.dealType==='Аренда'?property.rentalTerm:null]]}/><Detail title="Агент" items={[['Ответственный агент',property.agent],['Рекрут',property.recruit],['Telegram',property.agentTelegram],['Телефон',property.agentPhone]]}/><Detail title="Собственник" items={[['Имя',property.ownerName],['Телефон',property.ownerPhone],['Кадастровый номер',property.cadastralNumber],['Статус эксклюзива',property.exclusiveStatus],['Комментарий',property.comment]]}/></div>}
function Detail({title,items}:{title:string;items:[string,string|number|null|false][]}){return <section className="detail-panel"><h2>{title}</h2><Definition items={items}/></section>}
function Media({property}:{property:Property}){return property.media.length?<div className="media-gallery">{[...property.media].sort((a,b)=>a.order-b.order).map(item=><article key={item.id}>{item.type==='photo'?<img src={item.previewDataUrl} alt={item.name}/>:<video src={item.previewDataUrl} controls/>}<strong>{item.name}</strong><small>{item.isPrimary?'Главное · ':''}Оригинал · watermark не применён</small></article>)}</div>:<TabEmpty icon={<Camera/>} title="Медиа пока нет" text="Добавьте локальные фото или видео в режиме редактирования объекта."/>}
function Owner({property,onAssign}:{property:Property;onAssign:()=>void}){return <div className="detail-panel owner-panel"><h2>Собственник</h2><Definition items={[['Имя',property.ownerName],['Телефон',property.ownerPhone]]}/><div className="inline-actions"><Link className="button button--secondary" to={`/properties/${property.id}/edit`}>Редактировать данные</Link><button className="button" onClick={onAssign}>Назначить агента</button></div></div>}
function History({property}:{property:Property}){return property.history.length?<div className="history-list">{property.history.map(item=><article key={item.id}><span className="history-dot"/><div><strong>{item.field}: {item.action}</strong><p>{item.previousValue&&<><s>{item.previousValue}</s> → </>}{item.newValue}</p><small>{formatDate(item.createdAt)} · {item.author}</small></div></article>)}</div>:<TabEmpty icon={<ClipboardCheck/>} title="История пуста" text="Изменения объекта будут записываться автоматически."/>}
function Definition({items}:{items:[string,string|number|boolean|null][]}){return <dl className="definition-list">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Не указано'}</dd></div>)}</dl>}
function TabEmpty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="tab-empty"><span>{icon}</span><h2>{title}</h2><p>{text}</p></div>}
