import { ArrowLeft, Save } from 'lucide-react';
import { type FormEvent, type ReactNode, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { CURRENCIES, EMPTY_PROPERTY_INPUT, PROPERTY_SOURCES, PROPERTY_STATUSES, PROPERTY_TYPES, type PropertyInput } from '../../domain/property';
import { propertyRepository } from '../../repositories/propertyRepository';
import { propertyService, validateProperty } from '../../services/propertyService';
import './properties.css';

const numericFields = ['rooms','bedrooms','area','floor','totalFloors','price'] as const;
export default function PropertyFormPage() {
  const { propertyId } = useParams(); const navigate = useNavigate(); const existing = propertyId ? propertyRepository.getById(propertyId) : null;
  const [input,setInput] = useState<PropertyInput>(existing ? (({id,createdAt,updatedAt,history,...rest})=>rest)(existing) : EMPTY_PROPERTY_INPUT);
  const [errors,setErrors] = useState<Partial<Record<keyof PropertyInput,string>>>({}); const [submitError,setSubmitError]=useState(''); const [saving,setSaving]=useState(false);
  if (propertyId && !existing) return <Navigate to="/properties" replace/>;
  const set = <K extends keyof PropertyInput>(key:K,value:PropertyInput[K]) => { setInput(v=>({...v,[key]:value})); setErrors(v=>({...v,[key]:undefined})); };
  const submit=(event:FormEvent)=>{event.preventDefault(); const nextErrors=validateProperty(input); setErrors(nextErrors); if(Object.keys(nextErrors).length){document.querySelector<HTMLElement>('.field-error')?.focus();return;} setSaving(true); setSubmitError(''); try { const saved=existing?propertyService(propertyRepository).update(existing,input):propertyService(propertyRepository).create(input); navigate(`/properties/${saved.id}`); } catch(reason){setSubmitError(reason instanceof Error?reason.message:'Не удалось сохранить объект.');setSaving(false);} };
  return <section className="page property-form-page"><Link className="back-link" to={existing?`/properties/${existing.id}`:'/properties'}><ArrowLeft size={17}/>Назад</Link><header className="page__header"><div><p className="eyebrow">{existing?'Редактирование':'Новый объект'}</p><h1>{existing?'Редактировать объект':'Добавить объект'}</h1><p>Поля со звёздочкой обязательны.</p></div></header><form onSubmit={submit} noValidate>
    {submitError&&<div className="form-alert" role="alert">{submitError}</div>}
    <FormSection title="Учёт и источник"><Field label="Внутренний ID *" error={errors.internalId}><input value={input.internalId} onChange={e=>set('internalId',e.target.value)}/></Field><Field label="Источник"><select value={input.source} onChange={e=>set('source',e.target.value as PropertyInput['source'])}>{PROPERTY_SOURCES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Ссылка на источник" error={errors.sourceUrl} wide><input type="url" value={input.sourceUrl} onChange={e=>set('sourceUrl',e.target.value)} placeholder="https://…"/></Field></FormSection>
    <FormSection title="Расположение"><Field label="Адрес *" error={errors.address} wide><input value={input.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Район *" error={errors.district}><input value={input.district} onChange={e=>set('district',e.target.value)}/></Field><Field label="Кадастровый номер"><input value={input.cadastralNumber} onChange={e=>set('cadastralNumber',e.target.value)}/></Field></FormSection>
    <FormSection title="Характеристики"><Field label="Тип недвижимости"><select value={input.propertyType} onChange={e=>set('propertyType',e.target.value as PropertyInput['propertyType'])}>{PROPERTY_TYPES.map(v=><option key={v}>{v}</option>)}</select></Field>{numericFields.filter(v=>v!=='price').map(key=><Field key={key} label={({rooms:'Комнаты',bedrooms:'Спальни',area:'Площадь, м²',floor:'Этаж',totalFloors:'Этажность'} as const)[key]} error={errors[key]}><input type="number" min="0" step={key==='area'?'0.1':'1'} value={input[key]??''} onChange={e=>set(key,e.target.value===''?null:Number(e.target.value))}/></Field>)}</FormSection>
    <FormSection title="Стоимость"><Field label="Цена *" error={errors.price}><input type="number" min="0" value={input.price||''} onChange={e=>set('price',Number(e.target.value))}/></Field><Field label="Валюта"><select value={input.currency} onChange={e=>set('currency',e.target.value as PropertyInput['currency'])}>{CURRENCIES.map(v=><option key={v}>{v}</option>)}</select></Field></FormSection>
    <FormSection title="Собственник и работа"><Field label="Имя собственника"><input value={input.ownerName} onChange={e=>set('ownerName',e.target.value)}/></Field><Field label="Телефон собственника"><input type="tel" value={input.ownerPhone} onChange={e=>set('ownerPhone',e.target.value)}/></Field><Field label="Ответственный агент"><input value={input.agent} onChange={e=>set('agent',e.target.value)} placeholder="Введите имя агента"/></Field><Field label="Статус"><select value={input.status} onChange={e=>set('status',e.target.value as PropertyInput['status'])}>{PROPERTY_STATUSES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Комментарий" wide><textarea rows={5} value={input.comment} onChange={e=>set('comment',e.target.value)}/></Field></FormSection>
    <div className="form-actions"><Link className="button button--secondary" to={existing?`/properties/${existing.id}`:'/properties'}>Отмена</Link><button className="button" disabled={saving}><Save size={17}/>{saving?'Сохранение…':'Сохранить объект'}</button></div>
  </form></section>;
}
function FormSection({title,children}:{title:string;children:ReactNode}){return <fieldset className="form-section"><legend>{title}</legend><div className="form-grid">{children}</div></fieldset>}
function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:ReactNode}){return <label className={`form-field${wide?' form-field--wide':''}${error?' field-error':''}`} tabIndex={error?-1:undefined}><span>{label}</span>{children}{error&&<small>{error}</small>}</label>}
