import { ArrowDown, ArrowLeft, ArrowUp, ImagePlus, Save, Star, Trash2 } from 'lucide-react';
import { type ChangeEvent, type FormEvent, type ReactNode, useState } from 'react';
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom';
import { BEDROOMS, BUILDING_TYPES, CURRENCIES, DEAL_TYPES, DESIGNS, EMPTY_PROPERTY_INPUT, PET_POLICIES, PROPERTY_CONDITIONS, PROPERTY_SOURCES, PROPERTY_STATUSES, PROPERTY_TYPES, type AmenityKey, type MediaItem, type PropertyInput } from '../../domain/property';
import { propertyRepository } from '../../repositories/propertyRepository';
import { propertyService, validateProperty } from '../../services/propertyService';
import './properties.css';

const amenityLabels:Record<AmenityKey,string>={elevator:'Лифт',oven:'Духовка',parking:'Парковочное место',airConditioner:'Кондиционер',balcony:'Балкон',terrace:'Терраса',yard:'Двор',wifi:'Wi-Fi',television:'Телевизор',bathtub:'Ванна',shower:'Душ',dishwasher:'Посудомоечная машина',stove:'Плита',microwave:'Микроволновка',vacuum:'Пылесос',fireplace:'Камин'};
export default function PropertyFormPage(){
 const {propertyId}=useParams();const navigate=useNavigate();const existing=propertyId?propertyRepository.getById(propertyId):null;
 const [input,setInput]=useState<PropertyInput>(existing?(({id,createdAt,updatedAt,history,...rest})=>rest)(existing):EMPTY_PROPERTY_INPUT);const [errors,setErrors]=useState<Partial<Record<keyof PropertyInput,string>>>({});const [submitError,setSubmitError]=useState('');const [saving,setSaving]=useState(false);
 if(propertyId&&!existing)return <Navigate to="/properties" replace/>;
 const set=<K extends keyof PropertyInput>(key:K,value:PropertyInput[K])=>{setInput(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:undefined}))};
 const num=(key:'area'|'floor'|'totalFloors'|'maxTenants'|'bathrooms'|'price'|'deposit',value:string)=>set(key,value===''?(key==='price'?0:null):Number(value));
 const submit=(e:FormEvent)=>{e.preventDefault();const next=validateProperty(input);setErrors(next);if(Object.keys(next).length){document.querySelector<HTMLElement>('.field-error')?.focus();return}setSaving(true);setSubmitError('');try{const saved=existing?propertyService(propertyRepository).update(existing,input):propertyService(propertyRepository).create(input);navigate(`/properties/${saved.id}`)}catch(reason){setSubmitError(reason instanceof Error?reason.message:'Не удалось сохранить объект.');setSaving(false)}};
 const addMedia=(event:ChangeEvent<HTMLInputElement>)=>{const files=[...(event.target.files??[])];files.forEach(file=>{const reader=new FileReader();reader.onload=()=>{const item:MediaItem={id:crypto.randomUUID(),type:file.type.startsWith('video/')?'video':'photo',name:file.name,mimeType:file.type,size:file.size,order:input.media.length,isPrimary:input.media.length===0,isOriginal:true,previewDataUrl:String(reader.result),watermark:{enabled:false,version:null}};setInput(v=>({...v,media:[...v.media,item].map((x,i)=>({...x,order:i}))}))};reader.onerror=()=>setSubmitError(`Не удалось прочитать файл «${file.name}».`);reader.readAsDataURL(file)});event.target.value=''};
 const mediaAction=(id:string,action:'up'|'down'|'primary'|'delete')=>setInput(v=>{let media=[...v.media];const i=media.findIndex(x=>x.id===id);if(i<0)return v;if(action==='delete')media=media.filter(x=>x.id!==id);if(action==='primary')media=media.map(x=>({...x,isPrimary:x.id===id}));if(action==='up'&&i>0)[media[i-1],media[i]]=[media[i],media[i-1]];if(action==='down'&&i<media.length-1)[media[i+1],media[i]]=[media[i],media[i+1]];if(media.length&&!media.some(x=>x.isPrimary))media[0]={...media[0],isPrimary:true};return{...v,media:media.map((x,index)=>({...x,order:index}))}});
 return <section className="page property-form-page"><Link className="back-link" to={existing?`/properties/${existing.id}`:'/properties'}><ArrowLeft size={17}/>Назад</Link><header className="page__header"><div><p className="eyebrow">{existing?'Редактирование':'Новый объект'}</p><h1>{existing?'Редактировать объект':'Добавить объект'}</h1><p>Структура готова для будущего генератора публикаций. Поля со звёздочкой обязательны.</p></div></header><form onSubmit={submit} noValidate>{submitError&&<div className="form-alert" role="alert">{submitError}</div>}
 <Section title="1. Тип сделки"><div className="deal-selector form-field--wide">{DEAL_TYPES.map(v=><button type="button" key={v} className={input.dealType===v?'active':''} onClick={()=>set('dealType',v)}>{v}</button>)}</div></Section>
 <Section title="2. Основная информация"><Check label="Эксклюзивный объект" checked={input.exclusive} onChange={v=>set('exclusive',v)}/><Field label="Описание" wide><textarea rows={4} value={input.description} onChange={e=>set('description',e.target.value)}/></Field><Field label="Район *" error={errors.district}><input value={input.district} onChange={e=>set('district',e.target.value)}/></Field><Field label="Метро"><input value={input.metro} onChange={e=>set('metro',e.target.value)}/></Field><Field label="Адрес текстом *" error={errors.address}><input value={input.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Ссылка Google Maps" error={errors.googleMapsUrl}><input type="url" value={input.googleMapsUrl} onChange={e=>set('googleMapsUrl',e.target.value)} placeholder="https://maps.google.com/…"/></Field></Section>
 <Section title="3. Характеристики объекта"><Field label="Тип недвижимости"><Select values={PROPERTY_TYPES} value={input.propertyType} onChange={v=>set('propertyType',v)}/></Field><Field label="Спальни"><Select values={BEDROOMS} value={input.bedrooms} onChange={v=>set('bedrooms',v)}/></Field><Field label="Тип здания"><OptionalSelect values={BUILDING_TYPES} value={input.buildingType} onChange={v=>set('buildingType',v)}/></Field><Field label="Площадь, м²" error={errors.area}><input type="number" min="0" step="0.1" value={input.area??''} onChange={e=>num('area',e.target.value)}/></Field><Field label="Этаж" error={errors.floor}><input type="number" min="0" value={input.floor??''} onChange={e=>num('floor',e.target.value)}/></Field><Field label="Всего этажей" error={errors.totalFloors}><input type="number" min="1" value={input.totalFloors??''} onChange={e=>num('totalFloors',e.target.value)}/></Field><Field label="Дизайн"><OptionalSelect values={DESIGNS} value={input.design} onChange={v=>set('design',v)}/></Field>{input.dealType==='Аренда'?<Field label="Максимальное количество жильцов" error={errors.maxTenants}><input type="number" min="1" value={input.maxTenants??''} onChange={e=>num('maxTenants',e.target.value)}/></Field>:<Field label="Состояние объекта *" error={errors.condition}><OptionalSelect values={PROPERTY_CONDITIONS} value={input.condition} onChange={v=>set('condition',v)}/></Field>}</Section>
 <Section title="4. Удобства"><Field label="Количество ванных"><input type="number" min="0" value={input.bathrooms??''} onChange={e=>num('bathrooms',e.target.value)}/></Field><Field label="Тип отопления"><input value={input.heatingType} onChange={e=>set('heatingType',e.target.value)}/></Field><Field label="Питомцы"><Select values={PET_POLICIES} value={input.pets} onChange={v=>set('pets',v)}/></Field><div className="amenities-grid form-field--wide">{(Object.keys(amenityLabels) as AmenityKey[]).map(key=><Check key={key} label={amenityLabels[key]} checked={input.amenities[key]} onChange={value=>set('amenities',{...input.amenities,[key]:value})}/>)}</div></Section>
 <Section title="5. Цена и условия"><Field label="Цена *" error={errors.price}><input type="number" min="1" value={input.price||''} onChange={e=>num('price',e.target.value)}/></Field><Field label="Валюта"><Select values={CURRENCIES} value={input.currency} onChange={v=>set('currency',v)}/></Field>{input.dealType==='Аренда'?<><Field label="Депозит"><input type="number" min="0" value={input.deposit??''} onChange={e=>num('deposit',e.target.value)}/></Field><Field label="Ценовой диапазон"><input value={input.priceRange} onChange={e=>set('priceRange',e.target.value)}/></Field><Field label="Срок аренды"><input value={input.rentalTerm} onChange={e=>set('rentalTerm',e.target.value)} placeholder="Например, от 12 месяцев"/></Field></>:<Field label="Ценовой диапазон продажи"><input value={input.salePriceRange} onChange={e=>set('salePriceRange',e.target.value)}/></Field>}</Section>
 <Section title="6. Агент"><Field label="Ответственный агент"><input value={input.agent} onChange={e=>set('agent',e.target.value)}/></Field><Field label="Рекрут, если применимо"><input value={input.recruit} onChange={e=>set('recruit',e.target.value)}/></Field><Field label="Telegram username"><input value={input.agentTelegram} onChange={e=>set('agentTelegram',e.target.value)} placeholder="@username"/></Field><Field label="Телефон агента"><input type="tel" value={input.agentPhone} onChange={e=>set('agentPhone',e.target.value)}/></Field></Section>
 <Section title="7. Собственник"><Field label="Имя собственника"><input value={input.ownerName} onChange={e=>set('ownerName',e.target.value)}/></Field><Field label="Телефон собственника"><input type="tel" value={input.ownerPhone} onChange={e=>set('ownerPhone',e.target.value)}/></Field><Field label="Кадастровый номер"><input value={input.cadastralNumber} onChange={e=>set('cadastralNumber',e.target.value)}/></Field><Field label="Статус эксклюзива"><input value={input.exclusiveStatus} onChange={e=>set('exclusiveStatus',e.target.value)}/></Field><Field label="Комментарий" wide><textarea rows={4} value={input.comment} onChange={e=>set('comment',e.target.value)}/></Field></Section>
 <Section title="8. Медиа"><div className="media-upload form-field--wide"><label className="button button--secondary"><ImagePlus size={17}/>Добавить фото или видео<input hidden type="file" accept="image/*,video/*" multiple onChange={addMedia}/></label><p>Файлы не отправляются на сервер. Metadata и preview сохраняются локально в браузере.</p></div>{input.media.length>0&&<div className="media-editor form-field--wide">{input.media.map((item,i)=><article key={item.id}>{item.type==='photo'?<img src={item.previewDataUrl} alt={item.name}/>:<video src={item.previewDataUrl}/>}<div><strong>{item.name}</strong><small>{item.type==='photo'?'Фото':'Видео'} · {(item.size/1024/1024).toFixed(1)} МБ {item.isPrimary?'· Главное':''}</small><span>Оригинал: {item.isOriginal?'да':'нет'} · Watermark: будущая версия</span></div><div className="media-actions"><button type="button" onClick={()=>mediaAction(item.id,'up')} disabled={i===0} title="Выше"><ArrowUp/></button><button type="button" onClick={()=>mediaAction(item.id,'down')} disabled={i===input.media.length-1} title="Ниже"><ArrowDown/></button><button type="button" onClick={()=>mediaAction(item.id,'primary')} title="Сделать главным"><Star/></button><button type="button" onClick={()=>mediaAction(item.id,'delete')} title="Удалить"><Trash2/></button></div></article>)}</div>}</Section>
 <Section title="9. Системные поля"><Field label="Внутренний ID *" error={errors.internalId}><input value={input.internalId} onChange={e=>set('internalId',e.target.value)}/></Field><Field label="Источник"><Select values={PROPERTY_SOURCES} value={input.source} onChange={v=>set('source',v)}/></Field><Field label="Ссылка на источник" error={errors.sourceUrl}><input type="url" value={input.sourceUrl} onChange={e=>set('sourceUrl',e.target.value)} placeholder="https://…"/></Field><Field label="Статус объекта"><Select values={PROPERTY_STATUSES} value={input.status} onChange={v=>set('status',v)}/></Field>{existing&&<div className="system-dates form-field--wide"><span>Создан: {new Date(existing.createdAt).toLocaleString('ru-RU')}</span><span>Обновлён: {new Date(existing.updatedAt).toLocaleString('ru-RU')}</span><span>История: {existing.history.length} событий</span><span>Telegram: не опубликовано</span></div>}</Section>
 <div className="form-actions"><Link className="button button--secondary" to={existing?`/properties/${existing.id}`:'/properties'}>Отмена</Link><button className="button" disabled={saving}><Save size={17}/>{saving?'Сохранение…':'Сохранить объект'}</button></div></form></section>
}
function Section({title,children}:{title:string;children:ReactNode}){return <fieldset className="form-section"><legend>{title}</legend><div className="form-grid">{children}</div></fieldset>}
function Field({label,error,wide,children}:{label:string;error?:string;wide?:boolean;children:ReactNode}){return <label className={`form-field${wide?' form-field--wide':''}${error?' field-error':''}`} tabIndex={error?-1:undefined}><span>{label}</span>{children}{error&&<small>{error}</small>}</label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="check-field"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function Select<T extends string>({values,value,onChange}:{values:readonly T[];value:T;onChange:(value:T)=>void}){return <select value={value} onChange={e=>onChange(e.target.value as T)}>{values.map(v=><option key={v}>{v}</option>)}</select>}
function OptionalSelect<T extends string>({values,value,onChange}:{values:readonly T[];value:T|'';onChange:(value:T|'')=>void}){return <select value={value} onChange={e=>onChange(e.target.value as T|'')}><option value="">Не указано</option>{values.map(v=><option key={v}>{v}</option>)}</select>}
